INSERT INTO EMPLOYEE (LOGIN, NAME)
    VALUES('danielbayerlein', 'Daniel Bayerlein');
INSERT INTO EMPLOYEE (LOGIN, NAME)
    VALUES('danielkocot', 'Daniel Kocot');

INSERT INTO REPOSITORY VALUES(12345, 'danielbayerlein/foo', 'danielbayerlein');
INSERT INTO REPOSITORY VALUES(12346, 'danielbayerlein/bar', 'danielbayerlein');
INSERT INTO REPOSITORY VALUES(23456, 'danielkocot/baz', 'danielkocot');
INSERT INTO REPOSITORY VALUES(23457, 'danielkocot/helloworld', 'danielkocot');

INSERT INTO REPOSITORY_LANGUAGE VALUES('JAVA');
INSERT INTO REPOSITORY_LANGUAGE VALUES('GO');
INSERT INTO REPOSITORY_LANGUAGE VALUES('BASH');

INSERT INTO REPO_LANGUAGES VALUES(12345, 'JAVA');
INSERT INTO REPO_LANGUAGES VALUES(12345, 'GO');
INSERT INTO REPO_LANGUAGES VALUES(12346, 'GO');
INSERT INTO REPO_LANGUAGES VALUES(12346, 'BASH');
INSERT INTO REPO_LANGUAGES VALUES(23456, 'JAVA');
INSERT INTO REPO_LANGUAGES VALUES(23457, 'JAVA');

